modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issues_url}"

[[mods]]
modId="universal"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL=""
displayURL="${mod_display_url}"
logoFile=""
credits=""
authors="${mod_authors}"
displayTest="MATCH_VERSION"
description="${mod_description}"

[[dependencies.universal]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.universal]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
